auditbeat.modules:
- module: auditd
  resolve_ids: true
  failure_mode: silent
  backlog_limit: 8192
  rate_limit: 0
  # Load audit rules from separate files. Same format as audit.rules(7).
  audit_rule_files: [ '/usr/share/auditbeat/rules_folder/*.conf' ]


- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
